### ISSUE TITLE
yarn build

### ISSUE THREAD

**Issue by Best-Kevin** [jekip/naive-ui-admin-docs#2]
打包后静态资源报错，需要怎么修改

**Comment by jekip** [comment]
注意VITE_PUBLIC_PATH 配置，这个要根据部署情况修改，请参考文档部署章节

**Comment by Best-Kevin** [comment]
嗯嗯，我指的是“naive-ui-admin-docs”这个项目，打包的配置项没有找到

**Comment by Best-Kevin** [comment]
另外能否加大佬微信，本人开源项目：https://gitee.com/kevin_chou/qdpz，有个近400人开发群，希望能邀请大佬

**Comment by jekip** [comment]
可以，QQ群里私聊我吧
