### ISSUE TITLE
右侧和顶部 inverted 模式下的背景颜色颜色怎改变啊？对应css里是--color,看了半天文档也没有找到

### ISSUE THREAD

**Issue by cn-iz** [jekip/naive-ui-admin-docs#3]
![image](https://user-images.githubusercontent.com/37511469/137581920-0aab51bb-b201-4e70-bca0-f96f8cb3cfa7.png)

**Comment by jekip** [comment]
在，https://www.naiveui.com 官网，右下角主题编辑器中，找一下，然后在 app.vue中设置

在这个仓库，提相关问题吧，https://github.com/jekip/naive-ui-admin/issues
