### ISSUE TITLE
tableData属性后 不传request方法， 会报request is not a function， 并且如图的tableData3也不会显示，求指教

### ISSUE THREAD

**Issue by canyonwan** [jekip/naive-ui-admin-docs#4]
![image](https://user-images.githubusercontent.com/17877692/144749400-88974d07-0a51-4224-8e56-1d74ccffad13.png)
![image](https://user-images.githubusercontent.com/17877692/144749407-6f5a04f7-7f3f-45ce-b66b-b625515bc89b.png)
![image](https://user-images.githubusercontent.com/17877692/144749429-36dff707-ca94-4875-93cc-c003b76a249b.png)
您好， 在使用了tableData属性后 不传request方法， 会报request is not a function， 并且如图的tableData3也不会显示，求指教

**Comment by jekip** [comment]
在 https://github.com/jekip/naive-ui-admin/issues 反馈
